/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 07 06:13:12 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import javafx.stage.Stage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Desktop_ESTest extends Desktop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Desktop desktop0 = new Desktop();
      // Undeclared exception!
      try { 
        desktop0.browser();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class Core
         //
         verifyException("Desktop", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Desktop desktop0 = new Desktop();
      // Undeclared exception!
      try { 
        desktop0.updateWallpaper();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class Core
         //
         verifyException("Desktop", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Stage stage0 = Desktop.getAppWindow();
      assertNull(stage0);
  }
}
