/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 07 06:12:47 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SignOut_ESTest extends SignOut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SignOut signOut0 = new SignOut();
      // Undeclared exception!
      try { 
        signOut0.signOut(true);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class Core
         //
         verifyException("SignOut", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SignOut signOut0 = new SignOut();
      // Undeclared exception!
      try { 
        signOut0.signOut(false);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
      }
  }
}
